### ISSUE TITLE
[Bug] Unable to load robot symmetric representation. 

### ISSUE THREAD

**Issue by splendidsummer** [Danfoa/MorphoSymm#1]
# Issue 
With the provided permutation and reflection matrice in cfg yaml file,  I try to build the representations of Q_js and TqQ_js by using [load_symmetric_system](https://github.com/Danfoa/MorphoSymm/blob/cf4a6e8eede4f6124aceb5fb9f9266400184e420/morpho_symm/utils/robot_utils.py#L60), 
but it always causes an error from the builtin function [group_rep_from_gens](https://github.com/Danfoa/MorphoSymm/blob/cf4a6e8eede4f6124aceb5fb9f9266400184e420/morpho_symm/utils/robot_utils.py#L27) as follows:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[27], line 1
----> 1 G, value_in_type, policy_in_type, value_out_type, policy_out_type = load_cartpole_G()

Cell In[26], line 31, in load_cartpole_G()
     28     rep_po[g_gen] = gen_permutation_matrix(oneline_notation=perm, reflections=refx)
     30 # Generate the entire group
---> 31 rep_Q_js = group_rep_from_gens(G, rep_Q_js)
     32 rep_po = group_rep_from_gens(G, rep_po)
     33 rep_Q_js.name = 'Q_js'

File ~/autodl-tmp/MorphoSymm/morpho_symm/utils/group_utils.py:96, in group_rep_from_gens(G, rep_H)
     93     raise NotImplementedError(f"Group {G} not implemented yet.")
     95 # Convert Dict[GroupElement, np.ndarray] to escnn `Representation`
---> 96 rep_escnn = escnn_representation_form_mapping(G, rep_H)
     98 return rep_escnn

File ~/autodl-tmp/MorphoSymm/morpho_symm/groups/isotypic_decomposition.py:278, in escnn_representation_form_mapping(G, representation)
    276 rep(G.sample()).shape[0]  # Size of the representation
    277 # Find Q such that `iso_cplx(g) = Q @ rep(g) @ Q^-1` is block diagonal with blocks being complex irreps.
--> 278 cplx_irreps, Q = cplx_isotypic_decomposition(G, rep)
    279 # Get the size and location of each cplx irrep in `iso_cplx(g)`
    280 cplx_irreps_size = [irrep(G.sample()).shape[0] for irrep in cplx_irreps]

File ~/autodl-tmp/MorphoSymm/morpho_symm/groups/isotypic_decomposition.py:181, in cplx_isotypic_decomposition(G, representation)
    179 # Check if each subrepresentation can be further decomposed.
    180 for subrep in subreps:
--> 181     n_sub = subrep(G.sample()).shape[0]   # Dimension of sub representation
    182     is_irred, _ = is_complex_irreducible(G, subrep)
    183     if is_irred:

TypeError: 'dict' object is not callable

# Environment
Ubuntu 20.04 
Python 3.8.10 
Latest morpho_symm version

**Comment by splendidsummer** [comment]
I used the morpho_symm version which was published last week without this error, and obviously between these two versions the  brackets ('[' and ']') have been modified to parentheses in [this line](https://github.com/Danfoa/MorphoSymm/blob/cf4a6e8eede4f6124aceb5fb9f9266400184e420/morpho_symm/groups/isotypic_decomposition.py#L181C75-L181C75)

**Comment by Danfoa** [comment]
The problem should be solved with the latest commit. The entire Isotypic decomposition script assumes all representation instances are `Callables` and correspondingly uses the call operator () to query action representations. I.e., rep(g) -> nxn invertible numpy array.
