### ISSUE TITLE
Error when trying to launch basic visualization example

### ISSUE THREAD

**Issue by itaouil** [Danfoa/MorphoSymm#3]
When trying to launch the visualization example I get the following error:

![image](https://github.com/Danfoa/MorphoSymm/assets/17275225/52adba93-a30f-4e08-9c58-410363cca9de)

It seems like some of the representations in the robot_cfg dictionary are None. Any idea why?

**Comment by Danfoa** [comment]
Hi @itaouil Sorry for the errors. Made some changes without test. 

Will separate devel and main branches soon to avoid this annoying problems to the user.

Tell me if its ok, and I will close.

**Comment by itaouil** [comment]
It works now :)
