### ISSUE TITLE
I went through your source code recently and assume this line is not going to be used anywhere, so maybe  you could simply delete it in your later update~

### ISSUE THREAD

**Issue by splendidsummer** [Danfoa/MorphoSymm#6]
https://github.com/Danfoa/MorphoSymm/blob/c93f10eb97e2fe5438657a5df92545264d96d75d/morpho_symm/utils/rep_theory_utils.py#L129

**Comment by Danfoa** [comment]
Thank you very much for pointing this out @splendidsummer
