### ISSUE TITLE
The recursive usage of  group_rep_from_gens  are very interesting, but once again I assume these 2 line without any variables to get the returns are redudent code

### ISSUE THREAD

**Issue by splendidsummer** [Danfoa/MorphoSymm#7]
https://github.com/Danfoa/MorphoSymm/blob/29e0c0fe5281f13304437da492a7ca53d6b98595/morpho_symm/utils/rep_theory_utils.py#L91C1-L93C1

**Comment by splendidsummer** [comment]
I think I misunderstand the code here, never mind, I am going to close this stupid issue

**Comment by Danfoa** [comment]
Good catch. Thanks @splendidsummer will update soon, or feel free to do a PR if you want to :)
