### ISSUE TITLE
Request to include the UniTree Go2 robot in the library

### ISSUE THREAD

**Issue by DanielChaseButterfield** [Danfoa/MorphoSymm#8]
I would like to request that the UniTree Go2 robot be added to this library.

The URDF, xacro files, and other supporting materials for the Go2 robot can be found here: https://github.com/unitreerobotics/unitree_ros/tree/master/robots/go2_description

**Comment by Danfoa** [comment]
![go2-C2-symmetries_anim_static](https://github.com/Danfoa/MorphoSymm/assets/8356912/64d57399-18dc-4b93-a31d-8c4a7cd8dd1f)

Done :) 

If you have any questions let me know.

Thanks for the issue.
